### ISSUE TITLE
Chato.ps

### ISSUE THREAD

**Issue by Jamesford** [bramdevries/hubot-irail#1]
Hey, @bramdevries 

I saw your tweet about the errors you received on chato.ps. We've tweeted you back, but here's a little extra help. If you add the following yaml data, into a chatops.yaml file at the root of this repo, your custom script should work with your chato.ps bot.

``` yaml
name: irail
display: Irail
description: Get information about trains in Belgium from hubot
author: bramdevries
repo: https://github.com/bramdevries/hubot-irail
paths:
    - src/irail.coffee
commands:
    - nmbs help
    - nmbs from <station> to <station>
dependencies:
    - moment-timezone: '^0.3.0'
```
